### ISSUE TITLE
Add No Cruising code

### ISSUE THREAD

**Issue by cblevins** [regan008/MGG-LC-Data#21]
@regan008 Could you add the code you were using to generate the "no cruising" data to the end of https://github.com/regan008/MGG-LC-Data/blob/main/gg-mgg-geocoding-new.R so that it's outputting to [the final-output-folder](https://github.com/regan008/MGG-LC-Data/tree/main/final-output-data)? That way whenever I'm re-running geocoding for new years I can immediately add those and ahve it update in Tableau in one step. Thanks!

**Comment by cblevins** [comment]
We also probably should think about how we populate the Shiny app with updated data as well - whether we want to continue to just manually replace the files or integrate with the repostiroy so it's pulling directly from a single file (rather than having duplicates floating around). Definitely not urgent.

**Comment by regan008** [comment]
Yeah I was going to just build the shiny app within that repo but was having issues with file paths. We can look at fixing that in the future though so its drawing from the latest and greatest files in that folder. 

Will work on getting that code included right now.

**Comment by regan008** [comment]
Fixed with 2ef30e5 and 0ffabdd. I also reran the data files so those should be up to date now.
