### ISSUE TITLE
Refactor census map code

### ISSUE THREAD

**Issue by regan008** [regan008/MGG-LC-Data#23]
Hallie, I've created a new branch `census-map` for the map rather than dealing with a fork of the repo. You should:

1. clone this repo (be sure to use ssh)
2. checkout the `census-map` branch

In that branch you'll see a folder for the census map data and code. I've added it there initially and we'll eventually add it into the shiny app once its ready. 

I've adjusted the code you wrote. It now uses the ipumsr library and related functions for reading in and joining nhgis data. Note how this works. I also had to replace the shapefile and re-simplify it with mapshaper. Somewhere along the line of exchanging files in slack it got corrupted. 

There are two issues with the existing code that you should address to get this ready to go. Check off the below and reference the issue number in your commit as you go. (Remember to commit every meaningful change.)

- [x] Alaska isn't being properly filtered out. For now lets proceed with omitting Alaska and Hawaii - but we may want to add those back in later. 
- [x] Something is up with the scales on the map. I have not dug in so I'm not sure what but they certainly shouldn't all be roughly the same color. See if you can troubleshoot this. I think the map needs a scale. This should show the percentage of the total population that resides in each county/district. 
- [x] Lastly, the color that the map is using isn't ideal for analysis. All that blue looks the same to me. Can you use rcolor brewer and choose a better color scheme? Maybe diverging would be better? Check out https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

**Comment by Hmknipp** [comment]
Addressed these issues and pushing updated code

**Comment by regan008** [comment]
@Hmknipp I don't see a commit from you? Could check to see if it pushed?
